#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CrossBar.UI.Android.Resource", IsApplication=true)]

namespace CrossBar.UI.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Beer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BeerSearch = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BeerSearchResult = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Brewery = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BrewerySearch = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BrewerySearchResult = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SplashScreen = 2130903047;
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
